version: '3'
services:
  postgres:
    image: postgres:latest
    networks:
      - healty-net
    container_name: postgres-healty
    volumes:
      - postgres-db:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - healty-net
    container_name: pgadmin-healty
    volumes:
      - pgadmin-pg:/var/lib/pgadmin
    expose:
      - 15432
    ports:
      - 15432:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@teste.com
      - PGADMIN_DEFAULT_PASSWORD=admin
networks:
  healty-net:
volumes:
  postgres-db:
  pgadmin-pg: